### ISSUE TITLE
Errore durante l'inserimento di nuovi elementi nelle tabelle

### ISSUE THREAD

**Issue by marcoM32** [simeosoft/proci#3]
Durante l'inserimento di una specializzazione il campo ID non viene calcolato correttamente.

->Raggiungere la sezione "Gestione specializzazioni"
->Aggiungere una specializzazione
->Eliminare la specializzazione appena aggiunta
->Creare una nuova specializzazione

->La nuova specializzazione viene creata con ID=2 anche se non esiste nessuna ID=1

NB Questo comportamente succede in generale su tutte le tabelle.

**Comment by simeosoft** [comment]
Il campo id riflette il campo autoincrement sottostante quindi il comportamento non è modificabile.
In realtà non dovrebbe neanche essere visto dall'utente ma è visibile solo per comunicare con precisione un codice univoco.
